package com.ideathon.kondaeshield.analysis

internal data class KeywordRule(
    val phrase: String,
    val weight: Int = 1,
)

internal object NaggingKeywordRules {
    val blame = listOf(
        KeywordRule("왜 못해", 2),
        KeywordRule("왜 이래"),
        KeywordRule("그것도 못해", 2),
        KeywordRule("이걸 못해", 2),
        KeywordRule("똑바로 안 해", 2),
        KeywordRule("제대로 안 해"),
        KeywordRule("생각이 없어", 2),
        KeywordRule("정신 안 차려"),
        KeywordRule("문제야"),
        KeywordRule("잘못했어"),
        KeywordRule("네 탓", 2),
        KeywordRule("너 때문", 2),
        KeywordRule("핑계 대지 마"),
        KeywordRule("변명하지 마"),
        KeywordRule("한심하다", 2),
        KeywordRule("답답하다"),
        KeywordRule("실망이다"),
        KeywordRule("기본이 안 됐어"),
        KeywordRule("센스가 없어"),
        KeywordRule("일을 왜 이렇게 해", 2),
    )

    val comparison = listOf(
        KeywordRule("다른 사람은"),
        KeywordRule("남들은"),
        KeywordRule("누구는"),
        KeywordRule("걔는 하는데"),
        KeywordRule("쟤는 하는데"),
        KeywordRule("나는 했는데"),
        KeywordRule("나는 그때"),
        KeywordRule("나 때는"),
        KeywordRule("요즘 애들은", 2),
        KeywordRule("요즘 사람들은"),
        KeywordRule("너희 세대는"),
        KeywordRule("우리 때는"),
        KeywordRule("그 정도는 다 해"),
        KeywordRule("다들 하는데"),
        KeywordRule("이것밖에 못해"),
        KeywordRule("그 나이 먹고"),
        KeywordRule("아직도 이래"),
        KeywordRule("누구랑 비교하면"),
    )

    val command = listOf(
        KeywordRule("그냥 해"),
        KeywordRule("시키는 대로 해", 2),
        KeywordRule("말대꾸하지 마", 2),
        KeywordRule("토 달지 마"),
        KeywordRule("무조건 해"),
        KeywordRule("하라면 해"),
        KeywordRule("내 말 들어"),
        KeywordRule("내가 하라는 대로"),
        KeywordRule("묻지 말고 해"),
        KeywordRule("알아서 해"),
        KeywordRule("당장 해"),
        KeywordRule("빨리 해"),
        KeywordRule("다시 해"),
        KeywordRule("고쳐 와"),
        KeywordRule("보고해"),
        KeywordRule("이렇게 해"),
        KeywordRule("하지 마"),
        KeywordRule("그만해"),
        KeywordRule("말하지 마"),
    )

    val latte = listOf(
        KeywordRule("라떼는", 2),
        KeywordRule("나 때는 말이야", 2),
        KeywordRule("내가 예전에는"),
        KeywordRule("내가 너만 할 때는"),
        KeywordRule("내가 해봐서 아는데", 2),
        KeywordRule("내 경험상"),
        KeywordRule("옛날에는"),
        KeywordRule("우리 때는"),
        KeywordRule("예전엔 다"),
        KeywordRule("그때는 다"),
        KeywordRule("나는 그렇게 배웠어"),
        KeywordRule("나도 다 겪었어"),
        KeywordRule("그 정도 고생은"),
        KeywordRule("요즘은 편해"),
        KeywordRule("예전 사람들은"),
    )

    val practicalAdvice = listOf(
        KeywordRule("이렇게 해보면"),
        KeywordRule("다음에는"),
        KeywordRule("방법은"),
        KeywordRule("도움이 될 거야"),
        KeywordRule("같이 해보자"),
        KeywordRule("같이 보자"),
        KeywordRule("한번 해보자"),
        KeywordRule("어디서 막혔어"),
        KeywordRule("무엇이 어려웠어"),
        KeywordRule("이 부분부터"),
        KeywordRule("순서대로"),
        KeywordRule("정리해보자"),
        KeywordRule("개선해보자"),
        KeywordRule("확인해보자"),
        KeywordRule("연습해보자"),
        KeywordRule("도와줄게"),
        KeywordRule("필요하면"),
        KeywordRule("괜찮아"),
        KeywordRule("천천히 해도 돼"),
    )

    val intensifiers = listOf(
        "항상",
        "맨날",
        "도대체",
        "대체",
        "왜 항상",
        "또",
        "아직도",
        "이제 와서",
        "몇 번을 말해",
        "계속",
        "진짜",
        "너무",
    )
}
